name: sima_admin_web
description: Panel de administracion web para SIMA.
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: '^3.13.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/images/COLOR4.png
    - assets/images/3.png

  fonts:
    - family: TuFuente
      fonts:
        - asset: assets/fonts/BwGradualDEMO-Regular.otf
          weight: 400
        - asset: assets/fonts/BwGradualDEMO-Medium.otf
          weight: 500
        - asset: assets/fonts/BwGradualDEMO-Bold.otf
          weight: 700